### ISSUE TITLE
关于单词的难度d是如何调整的？

### ISSUE THREAD

**Issue by freerick137** [maimemo/SSP-MMC#1]
作者您好，您的工作给了我很大的启发，但是我有一点不明白。
论文中提到，一次Forget行为之后，单词的难度d会被提高𝜃3。这个参数是如何被训练得到的呢，我在代码中没能找到对应的部分。
在后面的SSP-MMC算法中，我注意到单词的难度被划分为了18个等级，每次Forget会在原来的难度上加2。这样设置背后考虑的原因是什么呢？期待您的解答

**Comment by L-M-Sherlock** [comment]
这个是人工确定的参数，因为这个算法在发论文的时候还没有实现BPTT。

**Comment by L-M-Sherlock** [comment]
加难度是为了让稳定性/半衰期增长更慢，这个是我们从数据中观察到的规律。

**Comment by L-M-Sherlock** [comment]
最新的算法在这里：https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Algorithm
