### ISSUE TITLE
data_preprocessing.py中的半衰期是如何计算的？

### ISSUE THREAD

**Issue by ZhaoYiShu-1** [maimemo/SSP-MMC#2]
作者您好，您的算法是我接触有关间隔重复的第一个算法，在该方面我还是个小白。
我目前对于cal_halflife函数中计算半衰期的理解是：把记忆的指数衰减模型取自然对数，将其转换为线性模型，这个斜率可以用来估计衰减率 λ，进而计算半衰期，但是我的不理解的是斜率为什么等于r_ivl_cnt/ivl_ivl_cnt？期待您的解答。

**Comment by L-M-Sherlock** [comment]
因为

$$ R = e^{\ln{0.9} \times \cfrac{I}{S}}$$

推出

$$ S = \cfrac{\ln 0.9}{\ln R} \times I =  \cfrac{\ln 0.9}{\frac{\ln R}{I}}$$

应用最小二乘法，得到

$$ \cfrac{\ln 0.9}{\frac{\sum\limits_i^n \ln R_i \times I_i\times cnt}{\sum\limits_i^n  I_i^2\times cnt}} $$
