### ISSUE TITLE
How to compute Table 3 of the Paper

### ISSUE THREAD

**Issue by CodePothunter** [maimemo/SSP-MMC#3]
First of all, I sincerely thank the authors for open-sourcing the datasets and codes, which provides an excellent platform for researchers to investigate English word memorization applications.

I'm trying to reproduce the results in Table 3 of the paper but encountering some difficulties. After going through the paper and code repository, I have the following questions:

1. How to reproduce the evaluation metrics in Table 3:
   - The evaluation function is defined in `model/dhp.py` but I couldn't find where this function is called
   - The code for 5-fold cross-validation mentioned in the paper seems to be missing
   - The implementation of baseline models (HLR, DASH, etc.) mentioned in Table 3 is not clear

2. Some model implementations seem unused:
   - `model/dhp.py` contains the DHP model implementation but is not referenced elsewhere
   - `model/sm2.py` contains the SM2 algorithm but also appears unused
   - The relationship between these model implementations and the simulation in `simulator.py` is unclear

3. Questions about the workflow:
   - The README describes the workflow from data preprocessing to simulation
   - However, it's not clear how to run the model evaluation process that produces Table 3's results
   - Are there any additional steps or scripts needed for model evaluation?

Could you please provide some guidance on:
1. How to properly run the model evaluation process
2. Where to find the cross-validation implementation
3. How these model implementations (`dhp.py`, `sm2.py`) should be used

This would be very helpful for researchers trying to reproduce the results or build upon this work.

**Comment by L-M-Sherlock** [comment]
<img width="510" alt="image" src="https://github.com/user-attachments/assets/43f8a087-6613-4ab2-830c-96248b03811c" />

This table is calculated from

https://github.com/maimemo/SSP-MMC/blob/1d474dd279493c7b3fe5658cb199277ccf43c70c/cal_model_param.py#L47-L50

https://github.com/maimemo/SSP-MMC/blob/1d474dd279493c7b3fe5658cb199277ccf43c70c/cal_model_param.py#L70-L73

**Comment by L-M-Sherlock** [comment]
The cross-validation is implemented here: 

https://github.com/maimemo/SSP-MMC/blob/1d474dd279493c7b3fe5658cb199277ccf43c70c/model/dhp.py#L63

**Comment by L-M-Sherlock** [comment]
> * The implementation of baseline models (HLR, DASH, etc.) mentioned in Table 3 is not clear

I didn't implement DASH. What do you mean here?

**Comment by L-M-Sherlock** [comment]
> * The code for 5-fold cross-validation mentioned in the paper seems to be missing

Which paper do you mention? The KDD paper doesn't implement 5-fold cross-validation.

**Comment by CodePothunter** [comment]
> > * The code for 5-fold cross-validation mentioned in the paper seems to be missing
> 
> Which paper do you mention? The KDD paper doesn't implement 5-fold cross-validation.

Sorry about this confusion. What I mean is that in the code it seems to have fold cross validation while the paper does not mention about this

**Comment by CodePothunter** [comment]
> > * The implementation of baseline models (HLR, DASH, etc.) mentioned in Table 3 is not clear
> 
> I didn't implement DASH. What do you mean here?

Ignore this comment 😭

**Comment by CodePothunter** [comment]
> <img alt="image" width="510" src="https://private-user-images.githubusercontent.com/32575846/396539603-43f8a087-6613-4ab2-830c-96248b03811c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDgwNTAsIm5iZiI6MTczNDQ0Nzc1MCwicGF0aCI6Ii8zMjU3NTg0Ni8zOTY1Mzk2MDMtNDNmOGEwODctNjYxMy00YWIyLTgzMGMtOTYyNDhiMDM4MTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDE1MDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NTg2ZTkwMWE2M2Q1YjdlYWQ2MTkxMTY0NTM1NDlmYjQxZmNmZjBlZWJiYTRmNzQ4MmZlYjA2NzM5M2QyZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1zHUrjQH42Ab-6yYuppn02HaglP1EVWxwaFFpyTgwaQ">
> This table is calculated from
> 
> https://github.com/maimemo/SSP-MMC/blob/1d474dd279493c7b3fe5658cb199277ccf43c70c/cal_model_param.py#L47-L50
> 
> https://github.com/maimemo/SSP-MMC/blob/1d474dd279493c7b3fe5658cb199277ccf43c70c/cal_model_param.py#L70-L73

Yes I have noticed about these codes which run on the `...for_visual.tsv`. therefore I'm not sure whether it works as it should be.

**Comment by CodePothunter** [comment]
Overall, my question raised when I was trying to adapt the evaluation settings to other memorization simulation models. Therefore I might need to adapt the way of data preprocessing fisrt and then adjust DHP, HLR models to meet new settings. However I haven't established a mature idea yet so I am still exploring with your codes.🥺 Thank you for your help.

**Comment by L-M-Sherlock** [comment]
> What I mean is that in the code it seems to have fold cross validation while the paper does not mention about this

Some codes were copied from my previous paper's project, so you can just ignore them.

> However I haven't established a mature idea yet so I am still exploring with your codes.

Feel free to ask questions!

**Comment by CodePothunter** [comment]
> > What I mean is that in the code it seems to have fold cross validation while the paper does not mention about this
> 
> Some codes were copied from my previous paper's project, so you can just ignore them.
> 
> > However I haven't established a mature idea yet so I am still exploring with your codes.
> 
> Feel free to ask questions!

Is FSRS-5 the new SOTA? In the `project page` of Open Spaced Repetition, I found you preparing to write a new paper about this (status: TODO).

**Comment by L-M-Sherlock** [comment]
> Is FSRS-5 the new SOTA? In the `project page` of Open Spaced Repetition, I found you preparing to write a new paper about this (status: TODO).

FSRS-5 is the new SOTA, and I lost the motivation to write a paper for that...

**Comment by CodePothunter** [comment]
> > Is FSRS-5 the new SOTA? In the `project page` of Open Spaced Repetition, I found you preparing to write a new paper about this (status: TODO).
> 
> FSRS-5 is the new SOTA, and I lost the motivation to write a paper for that...

Awesome! Is there any code for comparing the performance among FSRS-x models and the SSP-MMC model? I am new to this research area and I am thinking what contribution I can make to this community.

**Comment by L-M-Sherlock** [comment]
> Is there any code for comparing the performance among FSRS-x models and the SSP-MMC model?

They belong to different levels of the algorithm. SSP-MMC is the algorithm to find the optimal schedule, and FSRS is the the model to predict the memory. I have combined SSP-MMC and FSRS here: https://github.com/open-spaced-repetition/SSP-MMC-FSRS

**Comment by CodePothunter** [comment]
> > Is there any code for comparing the performance among FSRS-x models and the SSP-MMC model?
> 
> They belong to different levels of the algorithm. SSP-MMC is the algorithm to find the optimal schedule, and FSRS is the the model to predict the memory. I have combined SSP-MMC and FSRS here: https://github.com/open-spaced-repetition/SSP-MMC-FSRS

Cool! Is the TKDE paper the latest paper?

Also, I found a [benchmark](https://github.com/open-spaced-repetition/srs-benchmark) repo here. Is it a good start to kick off the research on memorization prediction? 

In the TKDE paper, the memory state is maintained and updated via a GRU-HLR model. How does it relate to the SOTA, GRU-P-short,in srs-benchmark?

**Comment by L-M-Sherlock** [comment]
> Cool! Is the TKDE paper the latest paper?

Yep, and the repo is: https://github.com/maimemo/SSP-MMC-Plus

**Comment by L-M-Sherlock** [comment]
> In the TKDE paper, the memory state is maintained and updated via a GRU-HLR model. How does it relate to the SOTA, GRU-P-short,in srs-benchmark?

They are different. The GRU in srs-benchmark is the GRU-HLR model in my TKDE paper.

**Comment by CodePothunter** [comment]
> > In the TKDE paper, the memory state is maintained and updated via a GRU-HLR model. How does it relate to the SOTA, GRU-P-short,in srs-benchmark?
> 
> They are different. The GRU in srs-benchmark is the GRU-HLR model in my TKDE paper.

![image](https://github.com/user-attachments/assets/45ba244a-88fe-453e-9c35-7155484810b1)
Is the right?

**Comment by L-M-Sherlock** [comment]
Yep.
